//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace George_BrownTeacher_Course_Management.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachersCours
    {
        public int TeacherId { get; set; }
        public string CourseNumber { get; set; }
        public string FirstName { get; set; }
        public string CourseTitle { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
